version: '3.1'

services:
  db:
    image: postgres
    container_name: api_nest
    environment:
      NODE_ENV: development
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - 'redis'

  redis:
    image: redis:6.2.3-alpine
    container_name: nestjs_redis_bull_redis
    ports:
      - '6379:6379'
    environment:
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10M'

volumes:
  postgres_data:
