@host = localhost
@port = 3000
@apiversion = api/v1

###
POST http://{{host}}:{{port}}/{{apiversion}}/auth/sign-up
Content-Type: application/json

{
  "name": "luan",
  "email": "john@acmeindc.com.br",
  "password": "W/54-mNLqUlUA0MnHn5cx4JfPux/8XK"
}

###
POST http://{{host}}:{{port}}/{{apiversion}}/auth/sign-in
Content-Type: application/json

{
  "email": "john@acmeindc.com.br",
  "password": "W/54-mNLqUlUA0MnHn5cx4JfPux/8XK"
}

###
POST http://{{host}}:{{port}}/{{apiversion}}/auth/password-recovery
Content-Type: application/json

{
  "email": "john@acmindc.com.br"
}

###
GET http://{{host}}:{{port}}/{{apiversion}}/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZGU3ODBiMC04ZTdmLTRlYTUtOTFiZi1lYmM2OGUxNjc4M2QiLCJlbWFpbCI6ImpvaG5AYWNtZWluYy5jb20uYnIiLCJuYW1lIjoiSm9obnMiLCJpYXQiOjE3MzMyNzc3MjcsImV4cCI6MTczMzM2NDEyN30.uO0hjlZAh8EWDx4ULzhRbyd0s8jj-s8ACCMpzbH3QMM

  